galaxyproject/ansible-galaxy-extras

templates/proftpd.conf.j2
Hi @jmchilton,
I found this nice trick to use environment variables inside of `proftpd.conf`.
I will need this for galaxy-stable. If you like it we can also replace `proftpd_files_dir`.
=> Use environment variables to set user permissions.

tasks/galaxy_root.yml, templates/nginx.conf.j2
* use nginx proxy
* serve static content
=> Expose the Galaxy report webapp on port 9003 via nginx.

templates/nginx.conf.j2
This is needed for https://github.com/bgruening/docker-galaxy-stable/issues/31 and potential debian packages.
=> Add new nginx location so we can set welcome_url to /etc/galaxy/

defaults/main.yml, templates/nginx.conf.j2
We can simply proxy to `galaxy_reports_port`. This will change the default port of reports from `9003` back to `9001`.
=> nginx_proxy_reports_port is not needed anymore. 

defaults/main.yml, tasks/galaxy_scripts.yml, tasks/main.yml, tasks/nginx.yml, tasks/startup.yml, templates/cgroupfs_mount.sh.j2, templates/create_galaxy_user.py.j2, templates/export_user_files.py.j2, templates/htpasswd.j2, templates/install_repo_wrapper.sh.j2, templates/startup.sh.j2, templates/supervisor.conf.j2
- Bring in runtime scripts from docker-galaxy-stable.
- Infrastructure for checking a directory and changing the UID based on that. Needed for https://github.com/galaxyproject/planemo/issues/212.
- Infrastructure for managing a tool shed in VM/container.
- Other small tweaks to supervisor configuration (galaxy needs more retries than it use to because postgres is taking awhile to setup - not sure what that is about or what changed).
=> [WIP] Standing PR containing enhancements for GCC 2015

templates/startup.sh.j2, templates/supervisor.conf.j2
This will help in solving https://github.com/bgruening/docker-galaxy-stable/issues/40.
@jmchilton please note that you need to set `UWSGI_PROCESSES=2`  and `UWSGI_THREADS=4` to use this role.
=> dynamic uwsgi processes and threads

templates/startup.sh.j2
@jmchilton what do you think? This is the most elegant solution I can think of. supervisor does not support `ENV_` in numprocs.
=> allow dynamic number of Galaxy handlers

templates/supervisor.conf.j2
[Distros should package uWSGI in a modular way, with each feature as a plugin. But when you install using language specific ways (pip, gem...) the relevant language is embedded, so you do not need to load the plugin] (http://stackoverflow.com/a/15941424)
I tested this with the stable branch of @bgruening docker-galaxy-stable, where this works fine.
(uwsgi is installed into the virtualenv environment using pip)
If we do have `--plugin python` in all of our current project, starting galaxy_web fails with
```
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
``` 
This has also occured [here](https://github.com/bgruening/docker-galaxy-stable/issues/76) …
=> plugin python is built into core uwsgi if installed via pip.

tasks/supervisor.yml, templates/supervisor.conf.j2
- 2d7774e stop supervisor during service management.
- 851f58c since the ENV variables are not available during `docker build` we don't start supervisor back up if we use ENV vars to control supervisor managed programs. [docker-galaxy-stable continues to work]
- 776ad83 on real machines (VM or bare metal), we need to create /var/run/postgresql with the proper permissions once after boot. This will run the install command once (`startsecs = 0`) after starting supervisor if we are not in docker. Same thing happens in init.d script supplied with ubuntu.
-  3b3a964 we still need PYTHONHOME for the handler, else handler jobs will fail while looking for sqlalchemy.orm.
=> venv fixes for galaxy-on-wheels and improvements for running outside of docker

defaults/main.yml, tasks/supervisor.yml, templates/supervisor.conf.j2
Changes:
Detect if proftp, posgresql, slurm or nginx were set to be controled by supervisor and deal with the systems services accordingly. 
Option to specify the Postgresql configure file added to supervisor.
=> Detect if proftp, posgresql, slurm or nginx are controled by supervisor

templates/nginx.conf.j2
Follow up to #50.
This is needed to get uploads to work when galaxy is not running at the root location.
=> Prefix upload related things.

defaults/main.yml, tasks/pbs.yml, tasks/supervisor.yml, templates/nginx.conf.j2, templates/supervisor.conf.j2
With these changes port 8800 doesn't need to be exposed anymore in the docker image if you just want to server jupyter/ipython. Doesn't work for RStudio unfortunately.
=> Proxy interactive environments

.travis.yml
As promised this PR will test the ansible role if it does not break the Docker Galaxy Image.
Testing now is a small chain of trust.
* bioblend has it's own unit-tests which tests a lot of functionality of a running Galaxy Server
* Galaxy Docker is using bioblend to run all tests against the Docker Image, ensuring a working Docker Image (which consumes a stable version of `ansible-galaxy-extras`)
* `ansible-galaxy-extras` is using a stable version of the Galaxy Docker Image and replaces the fixed stable `ansible-galaxy-extras`-role with a development version which need to be tested
This should ensure that all projects will work and are compatible. I hope it not to complex.
=> Enable role testing with the Galaxy Docker image

templates/supervisor.conf.j2
Otherwise, getting the following error:
```
Traceback (most recent call last):
File "/opt/galaxy/galaxy-app/tools/data_source/upload.py", line 18, in <module>
import galaxy.model  # noqa
File "/opt/galaxy/galaxy-app/lib/galaxy/model/__init__.py", line 21, in <module>
from sqlalchemy import and_, func, not_, or_, true, join, select
ImportError: No module named sqlalchemy
Traceback (most recent call last):
File "/opt/galaxy/galaxy-app/database/jobs/000/1/set_metadata_jruANb.py", line 1, in <module>
from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
File "/opt/galaxy/galaxy-app/lib/galaxy_ext/metadata/set_metadata.py", line 23, in <module>
from sqlalchemy.orm import clear_mappers
ImportError: No module named sqlalchemy.orm
```
=> Use the same galaxy environment for UWSGI and non-UWSGI setups.

templates/configure_slurm.py.j2, templates/job_conf.xml.j2
The default settings up to now result in GALAXY_SLOTS=1. With this PR users can
control the nativeSpecification parameter in the job_conf.xml using the
environmental variable NATIVE_SPEC.
We also set Shared=YES in the configure_clurm.py script. Shared=YES does not change the default
(https://computing.llnl.gov/linux/slurm/cons_res_share.html) unless --share
is provided to srun or the nativeSpecification in job_conf.xml.
=> Allow sharing nodes and set nativeSpecification for slurm.

templates/startup.sh.j2
This will enable Galaxy flavours with no classical Galaxy tool included by default.
=> Enable a bare Galaxy installation

defaults/main.yml, tasks/galaxy_root.yml, tasks/ie_proxy.yml, tasks/uwsgi.yml, templates/job_conf.xml.j2, templates/macros.xml.j2, templates/startup.sh.j2, templates/supervisor.conf.j2
In addition this PR introduces a macro file.
The PR is completely untested. Early feedback welcome.
Depends on https://github.com/galaxyproject/galaxy/pull/2278
=> WIP: add HTCondor support

templates/configure_slurm.py.j2
This should allow us to spin on some slurm images to form an ad-hoc slurm cluster for docker galaxy.
Ping @bgruening @afgane
=> Make control_machine and partition name configurable with env vars

defaults/main.yml
Has to be SHA1 instead of SHA-1 (causes
https://travis-ci.org/bgruening/docker-galaxy-stable#L3096)
Ping @afgane @bgruening
=> Typo in SqlAuthTypes default

tasks/slurm.yml, tasks/supervisor.yml, templates/startup.sh.j2, templates/supervisor.conf.j2
This fixes issue #81 (explained in detail there). Simply adds `|bool` filters to boolean variables in _when_ statements when the statement has an _and_ operator between the variables.
=> Hotfix: adds bool filters to booleans in when statements with and operators

tasks/pbs.yml, tasks/slurm.yml
psutil is nowadays in Galaxy and will be installed via Galaxy wheels. So we can remove it from this role. https://github.com/galaxyproject/galaxy/blob/431c7707b5f5d9f424267b8e059c2e2d42deb9df/lib/galaxy/dependencies/requirements.txt#L48
=> remove psutil

defaults/main.yml, templates/proftpd.conf.j2
I've not yet taken the step of removing the flag entirely, which would turn on sftp and ftp on together by default. I can't really imagine anyone *not* wanting the option of sftp, but maybe it makes sense to keep the flag. Let me know @martenson @mvdbeek @bgruening @jmchilton
=> Make ftp and sftp stand side by side, instead of replacing ftp with sftp

templates/startup.sh.j2
This is now needed as we are using the new postgresql ansible role.
=> Change postgresql data_directory to /export during startup

tasks/galaxy_metrics.yml, tasks/galaxy_root.yml, tasks/pbs.yml, tasks/slurm.yml
Variable `galaxy_log_dir` carries a default value and it is used in a number of tasks so ensure the given dir exists.
=> Make sure the Galaxy log dir exists.

meta/main.yml
This allows the role to be installed via `ansible-galaxy` command, which can be desirable in general and needed by https://github.com/ARTbio/GalaxyKickStart/issues/186.
=> Add role meta folder

tasks/main.yml, tasks/proftpd.yml, templates/startup.sh.j2
Added tags for nginx, proftpd, slurm.
startup.sh always creates the admin user in case it doesn't exist.
=> Tags and startup.sh

defaults/main.yml
@jmchilton do you know why this was set to `galaxy` there is no data-volume called galaxy available, isn't it.
=> Change galaxy_docker_volumes_from to ""

defaults/main.yml, templates/nginx_galaxy_web.conf.j2, templates/nginx_uwsgi.conf.j2
Hej,
I needed to add these to make the authentication work on my setup which looks like this:
The Internet --> nginx proxy doing auth with ldap module, filling a REMOTE_USER header --> nginx embedded in docker-galaxy-stable
=> Add remote_user header if received from another proxy

tasks/nginx.yml, templates/nginx.conf.j2, templates/nginx_reports_auth.conf.j2, templates/startup.sh.j2
Hej!
I'm running galaxy dockers behind a collection of proxies, with url prefixes and it was a bit complicated to configure until now. So I'm preparing a PR for https://github.com/bgruening/docker-galaxy-stable where I introduce a new env var (GALAXY_CONFIG_PROXY_PREFIX) which will magically make all changes necessary to make all components aware of the url prefix.
The main logic is in this PR, most of it is working on my test setup, though I'll do more tests next week.
Open to any suggestions of course!
Happy easter! 🥚 🥚 🥚
=> Configure proxy prefix

templates/supervisor.conf.j2
It seems this directory already exists and the permissions are wrong. This little hack shouldn't break the Docker version of munge and should fix the VM variant.
=> Fix munge in planemo machine's VM.

defaults/main.yml, tasks/slurm.yml, templates/container_resolvers_conf.xml.j2, templates/job_conf.xml.j2
[Updated to describe two commits.]
First commit enables using the ``docker_dispatch`` dynamic rule. GALAXY_DESTINATIONS_DEFAULT is the environment variable that sets the default job destination - this can be set "docker_dispatch" and then two new environment variables will be used - GALAXY_DESTINATIONS_DOCKER_DEFAULT and GALAXY_DESTINATIONS_NO_DOCKER_DEFAULT to determine the destinations for Docker and non-Docker jobs respectively.
The second commit allows fine grain determination of the container resolvers file used by Galaxy. I use this to enable direct annotation and existing BioContainers on quay - but disabling building containers on demand and checking the local Docker host for cached containers (since this isn't available in the Kubernetes setup).
=> Improvements for Containerized Execution of Jobs

tasks/slurm.yml
@jmchilton This may help planemo machine VM passing the test
=> suppress restart of service after munge install as it is not required

templates/startup.sh.j2
Adapt 2 more env vars when the galaxy docker is running behind a proxy
Discussed in https://github.com/bgruening/docker-galaxy-stable/pull/310
=> Change NGINX_X_ACCEL vars when using PROXY_PREFIX

defaults/main.yml, templates/job_conf.xml.j2
These break non 17.09+ Galaxies so I had to introduce a minimum target Galaxy version for the role that is being executed. I defaulted this to 17.01 for now - anyone using an older Galaxy with master of this role?
=> Allow environment variables to conditionally enabled Galaxy job runners.

defaults/main.yml, templates/nginx.conf.j2
Probably shouldn't break anything for existing setup since I don't think docker-galaxy-stable for instance was writing anything to /root/502.html right?
xref https://github.com/galaxyproject/ansible-galaxy/commit/1bff199822c7c8456a6d2ff802ec98732c57a4d0
xref https://github.com/galaxyproject/planemo-machine/issues/85
=> Synchronize nginx error doc handling with ansible-galaxy role.

templates/startup.sh.j2
Just a tiny patch to avoid a warning in the logs
=> Hide "no such file or directory" warning

templates/nginx.conf.j2, templates/supervisor.conf.j2
Default buffer size in uWSGI is 4096.
But it's small for long error message.
In my case , I try to import workflow  to clean docker galaxy instance ,
the galaxy instance has no tool for the workflow.
Error message is long , like this
```
/admin?status=error&message=Imported%2C+but+some+steps+in+this+workflow+have+validation+err
```
uwsgi.log error message has like this
```
invalid request block size: 4098 (max 4096).
```
but increase buffer size , there is no uwsgi error
=> Increase buffer size for uWSGI

defaults/main.yml, templates/job_conf.xml.j2, templates/macros.xml.j2
Flush out the job configuration file with many more job destinations, allowing different runtime defaults for the built containers using just the configuration variable GALAXY_DESTINATIONS_DEFAULT.
The options are:
- `local_no_container`: Use the local runner, do not use Docker.
- `local_docker`: Use the local runner along with Docker if a container for the tool can be found.
- `local_force_docker`: Use the local runner and force tools to use Docker*.
- `pbs_cluster`: Use PBS cluster without Docker.
- `pbs_cluster_docker`: Use PBS cluster with Docker if a container for the tool can be found.
- `pbs_cluster_force_docker`: Use PBS cluster and force tools to use Docker*.
- `slurm_cluster`: Use SLURM, do not use Docker.
- `slurm_cluster_docker`: Use SLURM and use Docker if a container for the …
=> Allow many more job runner options at runtime.

defaults/main.yml, tasks/ie_proxy.yml, templates/startup.sh.j2
- Added PULL_IE_IMAGES environmental variable to the startup script.
- Startup.sh is now able to load the required images in the background while Galaxy starts.
- Default IE images are updated to be the same as the Galaxy default images
- Removed references to deprecated ipython image.
This change was requested in https://github.com/bgruening/docker-galaxy-stable/issues/306
Hacked together at GCC2017 by @jvanbraekel, @thobalose and @rhpvorderman.
=> Preloading IE docker images in startup.sh

defaults/main.yml
PSU server is down at the moment, adding all servers should improve robustness (when I developed this I mistakenly thought that each server was responsible for one repository (test, main, data) of the galaxyproject.org set).
=> Add IU and TACC servers to cvmfs_server_urls

tasks/main.yml
Otherwise, Supervisor reports `can't find command '/usr/sbin/automount'`
Should address https://github.com/galaxyproject/ansible-galaxy-extras/issues/164
If the supervisor process status is still `FATAL` at the end of a build, it always clears for me after a reboot.
=> Move CVMFS setup before supervisor

tasks/cvmfs_client.yml
I see the following warning (?) in my logs with the new cvmfs setup. It seems to work without. Anyone knows if this is strictly needed?
```
root@92346ba6f12d:/galaxy-central# cvmfs_config chksetup
/usr/bin/cvmfs_config: line 578: uuidgen: command not found
OK
```
ping @afgane
=> Add uuidgen

.travis.yml, templates/startup.sh.j2, tests/conditional_deps/auth_conf.xml, tests/conditional_deps/test_script.sh
Plain galaxy starts using [common_startup.sh](https://github.com/galaxyproject/galaxy/blob/dev/scripts/common_startup.sh) which loads conditional requirements. For example if you have specified an auth_con.xml file in galaxy.ini it will load the python-ldap package. 
Unfortunately this feature was not present in docker-galaxy-stable. 
I copied the responsible script in common_startup.sh to startup.sh.j2 and tested it in the docker image by trying to authenticate on our own ldap server. 
It seems to work. All that required is that the FETCH_WHEELS environment variable is set to something other than "". If further modifications need to be made to properly integrate this please let me know.
=> Enable loading of conditional requirements in /usr/bin/startup

templates/supervisor.conf.j2
Hello; this is a fix for a situation where a user [specifies their own uwsgi_port in this role's default variables](https://github.com/galaxyproject/ansible-galaxy-extras/blob/7ab0cad82e71ed71678aa0443b5c7d9808439ed4/defaults/main.yml#L120). 
Port 4001 was hardcoded into the `supervisor.conf` template, so galaxy_web uwsgi instances were listening on that port, however `nginx.conf` [correctly picked up the new port](https://github.com/galaxyproject/ansible-galaxy-extras/blob/4b6344450ccd50d0b26806f3e0c1ed39b45aaeee/templates/nginx_uwsgi.conf.j2#L3) and was `proxy_pass`ing requests to the specified port.
With this minor alteration, nginx and uwsgi once again have a harmonious relationship.
*note: i wasn't able to find any other places where the port was hard-coded in, or any other …
=> fix for hard-coded uwsgi ansible variable uwsgi_port

tasks/k8.yml
This sets the version of pykube to 0.15.0, for stability of the k8s integration. As discussed in https://github.com/galaxyproject/galaxy-kubernetes/issues/2#issuecomment-336390996
=> Sets version for pykube library to 0.15.0 for k8s stability

defaults/main.yml, templates/job_conf.xml.j2
This PR adds some missing k8s plugin vars. As discussed in https://github.com/galaxyproject/galaxy-kubernetes/issues/2#issuecomment-336390996 .
Not sure if this might break something on older galaxy versions were the k8s runner wasn't aware of these additional vars. Please advise.
=> Initial defaults for missing k8s plugin vars

templates/proftpd.conf.j2
Issue:
galaxy_user_uid and galaxy_user_gid are hard coded to 512 in https://github.com/galaxyproject/ansible-galaxy-extras/blob/86a127ae3aaaea125c8faa0271471106f2a4f889/templates/proftpd.conf.j2#L80
This does not seem to cause problem for an installation under Ubuntu 14.04. In contrast, this causes an authentification error from proftpd under Ubuntu 16.04.
Fix:
replace `512,512` with `'{{ galaxy_user_uid }}','{{ galaxy_user_gid }}'`
Side notes:
I have doubts that the placeholders %{env:GALAXY_GID} and %{env:GALAXY_UID} are correctly substituted by the corresponding environment variables GALAXY_GID and GALAXY_UID, at least when defined in group_vars/all by:
```
- export GALAXY_GID="${GALAXY_GID:-{{ galaxy_user_gid }}}"
- export GALAXY_UID="${GALAXY_UID:-{{ galaxy_user_uid }}}"
```
for …
=> Adjust proftpd.conf.j2 variables

tasks/ie_proxy.yml
- As mentioned in [RTD](https://docs.galaxyproject.org/en/master/admin/interactive_environments.html), : 
```
if you have NodeJS installed under Ubuntu, it often installs to /usr/bin/nodejs, whereas npm expects it to be /usr/bin/node. You will need to create that symlink yourself.
```
- I find that Install proxy dependencies task as `galaxy` user fails. Is there any reason to do so ? My proposed cut allows ansible to install the nodejs proxy in all cases
=> fix ie_proxy.yml

.gitignore, templates/supervisor.conf.j2
In response to issue discussed in https://github.com/galaxyproject/ansible-galaxy-tools/issues/48,
here we propose to increase the strength of the signal termination sent by supervisor to uwsgi when stopping or restarting the galaxy:web_galaxy service.
This makes more robust the management of this service by a handler discussed in the issue
=> Change signal for stopping galaxy:galaxy_web to stopsignal=QUIT

tasks/nginx.yml
Ping @afgane, seems we do need this to complete the playbook for the
Oslo tutorial, because nginx only uses `mkdir`, not `mkdir -p` to create
the directory.
This reverts commit 7700237125fde70f6be5ef125d6a23f4dea013e1.
=> Revert "Remove explicit creation of the nginx upload_store dir"

templates/startup.sh.j2
This PR adds the ability for admins to add an script with logic that should be executed once the galaxy instance is running. `galaxy-wait` is part of ephemeris which is installed in the docker-stable compose images that are relevant to the `startup` script.
I modified slightly the way that the create-user is invoked, to better comply with its usage of admin email and admin user. Previously the email wasn't being used, which risks the admin not being blessed as such, but we can discuss this if needed. 
I have tested the functionality to work with my real use case.
This resolves #184
=> post-start-actions script placeholder

templates/nginx.conf.j2
to     location /_x_accel_redirect/ {
as explained in #183, nginx delegated downloads should not be prefixed even with prefixed galaxy frontend. In its current form, downloads fail for prefixed server instances.
=> Change location {{ nginx_galaxy_location }}/_x_accel_redirect {

defaults/main.yml, tasks/galaxy_extra_dependencies.yml, tasks/galaxy_root.yml, tasks/main.yml
This is mainly important for the docker-galaxy-stable image. It will have ldap and other python dependencies installed by default if this request is pulled. We could drop some of the dependencies to save space and let the startup script of #161 handle that in case someone needs an exotic dependency.
=> added installation of conditional dependencies

templates/supervisor.conf.j2
This PR addresses the issue described in https://github.com/bgruening/docker-galaxy-stable/issues/423. I would love to hear if you have been avoiding the `--thunder-lock` option for some reason, as in my local and OpenStack tests this looks good and seems to avoid the race condition previously described.
@natefoo any thoughts about usage of `--thuder-lock`?
Thanks!
=> Adds thunder-lock to avoid race conditions between multiple uwsgi threads

templates/startup.sh.j2
Doing some tests with galaxy-stable 17.09, I had problems with proxy_prefix and _x_accel_redirect.
It turns out it is a consequence of https://github.com/galaxyproject/ansible-galaxy-extras/pull/185, so here's a fix for it = remove the proxy_prefix from _x_accel_redirect in galaxy config too
I don't know yet if 18.01 was impacted too. I guess yes.
@drosofff can you confirm it's ok for you too?
=> Fix broken _x_accel_redirect and proxy_prefix

tasks/ie_proxy.yml
This allows allows building images again after issues described in #198, produced due to some issue in npm repo's certificate. I reckon this should be temporal and we might want to revert this later.
=> Trust insecure npm

defaults/main.yml, templates/supervisor.conf.j2
Fixes uwsgi start up by supervisor with old style galaxy.ini config file, ensuring compatibility with older galaxy release.
This fix was successfully tested on GalaxyKickStart
https://travis-ci.org/ARTbio/GalaxyKickStart/jobs/378385895
=> introduce a {{ galaxy_config_style }} variable

.travis.yml, ci_test_docker_galaxy.sh, ci_test_planemo_machine.sh
Re-organize test files and scripts to allow multiple test suites. Test updates against planemo machine and docker-galaxy-stable. Provides a clearer path toward integrating other external tests as well hopefully.
Final fix to fix https://github.com/galaxyproject/ansible-galaxy-extras/issues/40.
=> Multi-suite testing.

templates/nginx.conf.j2
I think packed has been deprecated as long as this project has existed.
=> Update for galaxyproject/galaxy#5094.

templates/nginx.conf.j2
=> Drop 'packed' path component for all nginx locations, it's just static now.

tasks/ie_proxy.yml
This change to work around failure to validate the SSL certificate for
deb.nodesource.com.
Using https was generating the following error on a base Ubuntu 14.04 LTS image:
```
TASK [galaxyprojectdotorg.galaxyextras : Check if the Ubuntu distro is supported] ***
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for deb.nodesource.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. …
```
=> Use http to validate Node distro support

templates/nginx.conf.j2
The same is being done in the usegalaxy.org template:
https://github.com/galaxyproject/usegalaxy-playbook/blob/8825178e89a49d611e92a5a01606dbaf8324c6d8/env/main/templates/nginx/usegalaxy.j2#L101
=> Fix missing favicon.ico

tasks/cvmfs_client.yml, tasks/ie_proxy.yml, templates/startup.sh.j2
I'm trying to fix errors in the galaxy docker compose images (a PR should come soon).
I found this problem with apt install of cvmfs, I *think* the key needs to be installed before adding the apt repo
=> [18.09] fix cvmfs install

defaults/main.yml, tasks/supervisor.yml, templates/startup.sh.j2
2 fixes for errors found in https://github.com/bgruening/docker-galaxy-stable/pull/464
- make sure cron is installed when it is managed by supervisor
- make sure the nginx upload module is not enabled when asking for https support. It is [disabled in http mode](https://github.com/bgruening/docker-galaxy-stable/blob/edbef97c5fa8f4d9d0f8e54db72b85bccba6d51e/compose/galaxy-web/Dockerfile#L61), but it was not specified here and it's [enabled by default](https://github.com/galaxyproject/ansible-galaxy-extras/blob/18.09/defaults/main.yml#L5).
=> [18.09] small fixes

tasks/cvmfs_client.yml
Another little fix, this time for cvmfs install: the stable apt repo contains packages for ubuntu 12.04, so it doesn't run on ubuntu 18.04 because libcrypto.so is not found.
Switching to `{{ ansible_distribution_release }}-prod` to get the good repo
=> [18.09] cvmfs version

templates/export_user_files.py.j2, templates/startup.sh.j2
Hi,
Here's a patch to ease my life: I have several small Galaxy containers running, and updating them is always a mess...
So I've made this patch to do this at startup:
- update most of the config sample files
- update the database (only if the new `GALAXY_AUTO_UPDATE_DB` is set)
- update all tools from the flavor yml list(s) (only if the path to yml file(s) is provided with the new `GALAXY_AUTO_UPDATE_TOOLS` var)
- update the conda install installed in /export/tool_deps (only if the new `GALAXY_AUTO_UPDATE_CONDA` is set)
Enabling all of this in a production instance could be quite risky :D. But well, for my instances it would save me a lot of headaches. And as it's disabled by default, I guess it shouldn't be a problem for other people.
Any comments welcome of course!
=> Auto-update galaxy at startup

templates/startup.sh.j2
A fix for a little bug found while testing the 18.09.1 docker image: bcftools env is installed as root, which can cause some permission problems when installing other envs later
=> Use galaxy user to install bcftools env

.travis.yml, ci_test_docker_galaxy.sh, ci_test_galaxykickstart.sh, tasks/galaxy_root.yml, tasks/slurm.yml, templates/configure_slurm.py.j2
Here is an attempt to improve the automatic tests for this repo.
- Since the `ci_test_docker_galaxy.sh` is failing since several months, I introduced a similar procedure which instead of being based on galaxy-docker-stable is based on [galaxykickstart](https://github.com/ARTbio/GalaxyKickStart.git).
- Before that, I had also worked a bit on the `ci_test_docker_galaxy.sh` issues and I kept some fixes in this PR (in particular the postgresql is now installed, see #237 ). There are still some fixes to be found but I did not had time to do it. To whom it may concern, I identified a strange issue with the apt-get install of condor package.
- The PR is doing a regular pip install of watchdog and slurm, as a turn around of #235. I saw that @bgruening is currently working on that and I will be …
=> Improve repo testing (introducing a galaxykickstart job)

.travis.yml, ci_test_galaxykickstart.sh, ci_test_planemo_machine.sh, tasks/ie_proxy.yml, tasks/slurm.yml
This one fixes the tests on the 19.05 branch.
I disable the planemo machine test for now as the docker image there would require some work due to python3 migration (I guess).
If there's no objections (and as I think everyone is busy!) I can:
- merge the 19.05 branch into master
- see if I can merge some pending PR
- start a 20.05 branch to make a few changes to allow updating https://github.com/bgruening/docker-galaxy-stable
=> Fix 19.05 tests

templates/create_galaxy_user.py.j2
The way this script is currently used in the docker image, it *should* update the existing user with a new password/api key. However, it doesn't.
This patch causes the script to update users even if they're already in the database. Thus, setting GALAXY_DEFAULT_ADMIN_PASSWORD and GALAXY_DEFAULT_ADMIN_KEY to different values at runtime will now work properly instead of silently failing to change the password/api key.
cc @bgruening
=> Allow updating an existing user

.travis.yml, ci_test_galaxykickstart.sh, templates/nginx.conf.j2, templates/proftpd.conf.j2, templates/supervisor.conf.j2
- Fix the supervisor.conf.j2 template, allowing nodejs to be found and started by supervisor
- Fix the proftpd.conf.j2, allowing proftpd to accommodate the current Galaxy password encoding
- connects with the new brand galaxykickstart (py3.7) for travis ci testing (this travis vm now turns green)
- my opinion in that docker testing could be suspended until it is fixed, but it is a question of taste (I prefer the green to the red) and not a call for that pr.
Feedbacks and improvements welcome before merging !
=> Fix supervisor and proftpd tasks, and repo testing by gks
