templates/nginx.conf.j2
This PR adds optional authentication if the file `/etc/nginx/htpasswd` exists.
=> Move the report webapp to :80/reports

templates/nginx.conf.j2
This should fix https://github.com/bgruening/docker-galaxy-stable/issues/48
=> Welcome page fix

defaults/main.yml, templates/job_conf.xml.j2, templates/nginx.conf.j2
Adding ability to define additional nginx config files to be included in the server definition.
=> Extra nginx config

templates/supervisor.conf.j2
This was changed in: https://github.com/galaxyproject/ansible-galaxy-extras/commit/f91c3d5427c4668bc96c4e39b29cdf44cd0d04db
=> Change supervisor_manage_nodeproxy to supervisor_manage_ie_proxy

tasks/slurm.yml
=> Handle the switch from eggs to wheels in a backwards compatible way

templates/startup.sh.j2
@jmchilton during the last month our startup script changed a lot. This is a try to merge back the changes.
=> update startup script that has changed during the month

templates/create_galaxy_user.py.j2
Needed to fix one bioblend test.
=> add default option to add a username to the script

defaults/main.yml, templates/supervisor.conf.j2
using `galaxy_uwsgi_static_conf`.
Use `postgresql_version` (also used in https://github.com/galaxyproject/ansible-postgresql) to determine location of postmaster binary and `supervisor_postgres_database_path`.
=> Make specifying uwsgi parameters with environmental variables optional

.travis.yml, tests/syntax.yml
=> Add travis syntax check

defaults/main.yml, tasks/galaxy_root.yml, tasks/ie_proxy.yml, tasks/slurm.yml, templates/create_galaxy_user.py.j2, templates/nginx.conf.j2, templates/startup.sh.j2, templates/supervisor.conf.j2
This will conflict #47 so that should be closed out first.
=> Switch galaxy_root to galaxy_server_dir to bring in line ansible-galaxy.

templates/startup.sh.j2
Thanks to @jmchilton for the pointer.
=> Use default bare tool_conf.xml

templates/job_conf.xml.j2, templates/supervisor.conf.j2
This seems like a pretty clean way to solve #63.
(The egg removal has nothing to do with conda)
=> Source venv in cluster destination and remove egg references

defaults/main.yml, templates/proftpd.conf.j2
and allow configuration of ftp port. Thanks to @fabiorjvieira for the PKDF2
config.
=> Add support for PBKD2 to proftpd

templates/startup.sh.j2
ping @mvdbeek
Any reasons to not alias localhost?
=> This is needed for the Docker compose work

defaults/main.yml, tasks/pbs.yml, tasks/slurm.yml, templates/job_conf.xml.j2
Describe other possibilities to control GALAXY_SLOTS / ntask and tag
job_conf.xml setup.
=> Make slurm ntask variable configurable

handlers/main.yml, handlers/restart_nginx.yml, tasks/nginx.yml
This should solve the recent test failures. Use capitals for the handler, since we do that in ansible-galaxy-tools as well.
Ping @bgruening
=> Add Restart Nginx handler

defaults/main.yml, templates/startup.sh.j2, templates/supervisor.conf.j2
=> Add NONUSE option for condor in startup

defaults/main.yml, tasks/proftpd.yml, templates/proftpd.conf.j2
I moved this from my master branch into an actual branch and the previous (#83) PR disappeared.
=> Allow for SFTP instead of FTP

templates/export_user_files.py.j2
The one upstream should be deleted, so that there is no confusion anymore.
=> update the export_user_file.py changes with the upstream one

tasks/galaxy_scripts.yml, templates/check_database.py.j2, templates/create_galaxy_user.py.j2, templates/startup.sh.j2
Fixed order of commands (also for DISABLE_REPORTS_AUTH).
Added quotes as mentioned in #116 
Cleaned up create_galaxy_user.py
Added check_database.py
=> Order of commands

templates/startup.sh.j2
Fixed bug which prevented postgresql to start using the non-autostart version.
=> Fixed startup.sh

defaults/main.yml, tasks/main.yml, templates/export_user_files.py.j2, templates/nginx.conf.j2, templates/startup.sh.j2, templates/supervisor.conf.j2
Added more configurations, tags, startup exclusion for postgres, lock mechanism for dock compose containers in init script
=> Changes for docker galaxy compose setup

.travis.yml, defaults/main.yml, tasks/proftpd.yml, templates/install_repo_wrapper.sh.j2
Proftpd option not to regenerate ssh keys, install-repository option for specifying the target instance
=> More options for compose setup

tasks/galaxy_root.yml
This will save us 200MB in all containers.
=> respect the GALAXY_VIRTUAL_ENV 

tasks/supervisor.yml
I don't think this is needed and I have problems if I only include a uwsgi from pip.
=> remove uwsgi restart

tasks/nginx.yml, templates/nginx_reports_auth.conf.j2, templates/nginx_reports_noauth.conf.j2, templates/startup.sh.j2
Not very elegant I'm afraid, but it should fix #130 hopefully.
@drosofff can you test it?
=> Possible fix for nginx startup failing (#130)

tasks/slurm.yml, templates/munge.service.j2
by pre-uploading a munge.service config file with
```
ExecStart=/usr/sbin/munged --syslog
```
The issue is detailed in #136
=> Fix installation of munge package in ubuntu 16.04

defaults/main.yml, tasks/k8.yml
TODO: Check if gcc is available.
=> Don't attempt to install urllib3[secure] if gcc is unavailable.

defaults/main.yml, templates/job_conf.xml.j2, templates/macros.xml.j2
@jmchilton this add singularity to SLRUM, we can add many more later.
I have tried to unify the macros even more, but ended up with the current solution, it was getting to ugly with nested variables and so on. However, I ended up with `container_type` and `force_container` to make it more general.
=> Add initial singularity support

defaults/main.yml, templates/startup.sh.j2
Adding on work done with @jvanbraekel and @rhpvorderman at GCC2017 Hack.
=> Added IE images.

defaults/main.yml, tasks/cvmfs_client.yml
As pointed out by @natefoo during a post-merge review in https://github.com/galaxyproject/ansible-galaxy-extras/pull/160
=> CVMFS additions 

tasks/ie_proxy.yml
My major contribution to repair galaxy_extras_ie_juypter_image in tasks/ie_proxy.yml. High level coding...
=> repair galaxy_extras_ie_juypter_image

tasks/uwsgi.yml
Sorts failing build of dockerfile on compose setup.
=> pins uwsgi version to 2.0.15

tasks/nginx.yml, templates/startup.sh.j2
With this PR PROXY_PREFIX should now work with the new galaxy.yml
Cheers
=> Support PROXY_PREFIX in 18.01

tasks/nginx.yml
So here's the little change we talked about in https://github.com/galaxyproject/ansible-galaxy-extras/pull/194
=> PROXY_PREFIX + 18.01, 2nd

defaults/main.yml, tasks/cvmfs_client.yml
Should work around certificate issues due to python < 2.7.6 in https://travis-ci.org/galaxyproject/ansible-galaxy-extras/jobs/395579717#L3504
=> Use apt to install cvmfs

defaults/main.yml, tasks/pbs.yml, tasks/slurm.yml
@mvdbeek (in response to https://github.com/galaxyproject/ansible-galaxy-extras/pull/217):
something like that ?
=> Drop egg support in tasks/slurm.yml

templates/startup.sh.j2
This should help people with local Vis and IEs.
=> run ./scripts/plugin_staging.py during startup

templates/nginx.conf.j2
and other headers with underscores
=> Add required config for REMOTE_USER

templates/startup.sh.j2, templates/startup_lite.sh.j2
Fix for the problem described here https://github.com/bgruening/docker-galaxy-stable/issues/562
As suggested by @AndreasSko 
I was wondering how these changes will get into galaxy-stable if the gitmodule is referring to branch = 20.05
NOTE: Adds new dependency netcat.
=> Better Postgres check
